VIA_ENABLE =			yes
VIAL_ENABLE =			yes

SERIAL_DRIVER =			usart

QMK_SETTINGS =			yes
UNICODE_ENABLE =		yes
MOUSEKEY_ENABLE =		yes
EXTRAKEY_ENABLE =		yes
NKRO_ENABLE =			yes
KEYBOARD_SHARED_EP =	yes

VIAL_INSECURE =			yes
CONSOLE_ENABLE =		yes

MOUSE_SHARED_EP =		no
COMMAND_ENABLE =		no
SPLIT_KEYBOARD =		no
BACKLIGHT_ENABLE =		no
RGBLIGHT_ENABLE =		no
AUDIO_ENABLE =			no    
BOOTMAGIC_ENABLE =		no

# project specific files
CUSTOM_MATRIX =			lite
SRC +=					matrix.c
QUANTUM_LIB_SRC +=		uart.c
